name: Deploy and Run JFrog Worker - xray-data-extractor

on:
  workflow_dispatch:
    inputs:
      build_name:
        description: 'Build name for Xray analysis'
        required: true
        default: 'example-build'
      build_number:
        description: 'Build number for Xray analysis'
        required: true
        default: '1'
  push:
    branches:
      - main

jobs:
  test-deploy-run:
    name: Test, Deploy & Run Worker
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm ci

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://psemea.jfrog.io
        with:
          oidc-provider-name: fabien-github

      - name: Run JFrog CLI audit (local security scan)
        run: |
          jf audit --local

      - name: Dry-run Worker
        run: |
          jf worker dry-run '{}'

      - name: Deploy Worker
        run: |
          jf worker deploy

